# =====================================================================================
# Wrangler Configuration for Authio RPC Worker
# Version: 13.0.0
# =====================================================================================
name = "authio" # Renamed for clarity as a standalone service
main = "src/index.mjs" # Changed to the new RPC entry point
compatibility_date = "2025-09-08" # This is later than the required 2024-04-03 for RPC

[assets]
directory = "./public"
binding = "ASSETS"

# --- KV Namespace Binding for User Store ---
# This binding connects the worker to the KV namespace managed by the `authello` project.
[[kv_namespaces]]
binding = "AUTH_USERS_KV"
id = "your_kv_namespace_id_here" # Replace with the ID from your Cloudflare dashboard

[vars]
# --- Authio UI & Routing Paths ---
LOGIN_URL_PATH = "/login"
LOGIN_ASSET_PATH = "./login.html"
AUTH_REDIRECT_PATH = "/"

# --- Authio API Route Paths ---
LOGIN_API_PATH = "/api/auth/login"
LOGOUT_API_PATH = "/api/auth/logout"

# --- Authio Identifiers ---
AUTH_COOKIE_NAME = "__authio_jwt"
AGENT_HEADER_NAME = "X-Authio-Token"

# --- Authio Security ---
JWT_SECRET = "your-super-secret-key-that-is-at-least-32-characters-long"
SESSION_TIMEOUT = 3600 # 1 hour

# --- Authio JWT Registered Claims ---
JWT_ISSUER = "https://auth.proxy.example.com"
JWT_AUDIENCE = "https://api.proxy.example.com"

# --- Authio Logging Configuration ---
AUTH_LOG_ENABLED = true
AUTH_LOG_LEVEL = "info"

# --- Authio Caching ---
CACHE_TTL_MS = 60000
MAX_CACHE_SIZE = 50000
CACHE_EVICTION_BATCH_SIZE = 100
USER_CACHE_TTL = 60 # In-memory cache TTL for a user object from KV, in seconds.

# --- Rate Limiter Binding ---
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

# --- Authio Analytics Engine Bindings ---
[[analytics_engine_datasets]]
binding = "AUTH_EVENTS"
dataset = "auth_events"

[[analytics_engine_datasets]]
binding = "AUTH_SUCCESS"
dataset = "auth_success"

[[analytics_engine_datasets]]
binding = "AUTH_FAILURES"
dataset = "auth_failures"